### ISSUE TITLE
[DXVA2] Hardware acceleration / ffmpeg DXVA2 won't work (Windows 10 x64)

### ISSUE THREAD

**Issue by ktox** [zaps166/QMPlay2#118]
Hi! First of all, let me say I love this program! I use it a lot for YouTube and listening to stuff using Audio-only streams. Thanks so much for it!

Now, while watching a 1080p 60fps YT video, I noticed high usage % on the CPU, something that should *not* happen while under Hardware Acceleration (~*30*-*40%* vs FF/Chrome's *3*-*5%* CPU):  
![](http://i.imgur.com/Y9JpmUE.jpg)

Checking *Settings*>*Playback*, found out the **Software decoder** was set first:  
![](http://i.imgur.com/jh3XDqO.jpg)
![](http://i.imgur.com/PPGDqUg.jpg)

So I tried changing it, and set **DXVA2 Decoder** first while removing **ffmpeg's Software Decoder**...  
![](http://i.imgur.com/gy49vpr.jpg)

...But was presented with this *error* message instead (swapping **DirectDraw**'s and **OpenGL 2**'s order had the same result):  
![](http://i.imgur.com/2cV6sel.jpg)

Finally, removing **OpenGL 2** and **ffmpeg's Software Decoder** from the list would make QMPlay2 unable to play anything. Anything would just start with "*Opening*" followed by a quick "*Stopped*".  
![](http://i.imgur.com/M7fnz2d.jpg)

My specs are:  
- Windows 10 x64
- Intel Core i5 750
- 4GB DDR3 RAM
- XFX ATi HD5850 / Radeon Crimson Drivers 16.2.1 (last available drivers for 5800 series!)

I can assure you DXVA2 works fine in other applications, such as browsers, Kodi and MPC-HC 1.7.13; and I run OpenGL regularly as part as a Computer Graphics course. Also, I tried downloading the lastest version and running it as "portable", as well as updating ffmpeg's .dlls to 3.3.3, both with no luck.  
If there's any way to gather logs of some sort, let me know and I'll gladly bring them to you.  
Thanks a lot! Regards :)

**Comment by zaps166** [comment]
Hi!

Could you check if your graphics driver supports "WGL_NV_DX_interop" ? You can download & run [this tool](http://glew.sourceforge.net/)  and send me output file :)

---

Unfortunately QMPlay2 doesn't have Direct3D video output - it only has OpenGL, so the "WGL_NV_DX_interop" extension is necessary to get DirectX video frame and put it into OpenGL. It is available on NVIDIA GPUs (all modern GPUs, maybe also on older) and Intel (for sure since HD4000, but maybe earlier). I haven't tested any AMD Radeon GPUs with DXVA2 yet.

---

You can try to open DXVA2 settings and select "Copy decoded video to CPU memory..." (and apply). This can be slow (or very slow), but it is good to test it whether DXVA2 works :)

**Comment by ktox** [comment]
Here! [visualinfo.txt](https://github.com/zaps166/QMPlay2/files/1288937/visualinfo.txt) and [glewinfo.txt](https://github.com/zaps166/QMPlay2/files/1288949/glewinfo.txt)

> You can try to open DXVA2 settings and select "Copy decoded video to CPU memory..." (and apply)

Tried it just now -- here're my findings!  
- "Partiatly checked" option won't work, shows the same OpenGL error message (*can't init textures*).  
- Fully checked and with Software decoder disabled works! No audio, though.  
- Fully checked and Software enabled, works! But its sluggish as hell, 60fps YT drops to 0fps during playback, and memory consumption jumps from <50 MB to ~200 MB.  
Ignoring all these drawbacks, Information panel *does* show it's using DXVA!  
**Stream 1** - *FFmpeg/DXVA2, OpenGL 4.5*

Maybe the problem lies with OpenGL 4.5? While skimming through those logs you requested, I found out many 4.5 features aren't particularly available for my GPU :(

Thanks for the quick reply, zaps! Hope we can get this solved soon :D

**Comment by zaps166** [comment]
Your logs contains WGL_NV_DX_interop and all OpenGL required functions, so it is OK. I have an old Radeon HD 5xxx somewhere, so I can check this soon :)

> No audio, though.

Yeah, because you disabled FFmpeg software decoder which decodes audio :) Software decoder decodes both: audio and video, but if you put video HW decoder as first then HW will be used (if possible) - no need to disable :)

> Maybe the problem lies with OpenGL 4.5?

OpenGL2 plugin requires (as its name) at least OpenGL 2.x or higher (or GLES2/GLES3). But HW decoders which use OpenGL might require higher level (I don't remember which... :D)

---

I really should add better logs for QMPlay2...

**Comment by zaps166** [comment]
The same problem od Radeon HD5450

**Comment by zaps166** [comment]
I've configured everything I need to develop on real Windows machine (no chance to fix it by cross-compile on Linux & reboot) 😄 I know what's wrong and I'll try to fix it soon.

**Comment by zaps166** [comment]
Done, tested on Radeon HD5450, the same drivers.

> 60fps YT drops to 0fps during playback

Also [added](https://github.com/zaps166/QMPlay2/commit/0273a4e603fa1534d5b34cee9798f88e5c555891) frame skipping for HWAccels. Btw. my HD5450 is too slow for 60 FPS 1080p movies, so it is not smooth (also on other software) - better use CPU in HD5450 case.

**Comment by zaps166** [comment]
> 60fps YT drops to 0fps during playback

On Radeon HD5450 and 60 FPS 1080p movie "Copy decoded video to CPU memory..." was a little faster (maybe direct DirectX<->OpenGL communication in Radeon drivers is bad or I'm doing something wrong...).

**Comment by ktox** [comment]
Wow, that was quite fast! Thanks for taking your time to find a solution, and this quick too :D  
Mind if I ask what was wrong or missing?

Will try this out in the next build and come back with results -- if for some reason it _still_ doesn't work (which I doubt), I'd gladly help you find the problem testing it out for you (so you don't have to waste your time installing that old HD5450 again haha).

Regards!

**Comment by zaps166** [comment]
> Mind if I ask what was wrong or missing?

https://github.com/zaps166/QMPlay2/commit/292a98cefb469c9704bc0de60c514bc8ec5e41f5

The problem is with DirectX<->OpenGL communication. IMHO AMD Radeon driver bug. Intel also has a bug in their drivers, so I've made a workaround to not release render targets on every resize, etc., but reuse them. Render targets are freed when playback is stopped. But on Radeon drivers (tested on beta for HD 5xxx) has problems when render target is reused - it doesn't work (first usage is test which passed, second is playback, so it didn't work at all). On nvidia drivers both cases works properly.
Solution: detect Intel driver and use workaround which is needed only for Intel.

> Will try this out in the next build

I can send you a build for test, it is 2 min for me to create an installer for Windows.

**Comment by ktox** [comment]
> But on Radeon drivers (tested on beta for HD 5xxx) has problems when render target is reused - it doesn't work (first usage is test which passed, second is playback, so it didn't work at all).


> IMHO AMD Radeon driver bug.

Ohhh that makes sense... I've heard it time and time again in Dolphin emu's blogs about these unexpected bugs / behaviour in drivers, especially on OpenGL :(  
How did you realise *that* was the problem, if it's not much to ask?

> I can send you a build for test, it is 2 min for me to create an installer for Windows.

Please do. I have the building environment set up on another PC, an old 32-bit Linux, where I needed to build it from source :P  
In this Windows machine I'd have to download and set up everything just to try this out, so I'll really appreciate it -- in the case we'd need to keep testing it, I'd gladly get it up and running!

Regards

**Comment by zaps166** [comment]
> How did you realise that was the problem, if it's not much to ask?

QMPlay2 doesn't have much logs, so I've added some logs to function which fails (init textures). Then I know where it fails. It fails on playback, because first test run passed, so I know that something fails at second attempt. The function which failed uses render target and I have workaround for Intel with it, so I've removed the Intel workaround and it starts working (Intel also has a bug with DX<->GL) 😃 

---

Temporary pre-release: https://github.com/zaps166/QMPlay2/releases/tag/17.09.11

**Comment by ktox** [comment]
> QMPlay2 doesn't have much logs, so I've added some logs to function which fails (init textures).
  
Glad to know sending those pics helped with isolating the problem!

> Temporary pre-release  

Much appreciated!  
I've tested it, and while **it works**, sadly it's not there 100% :( (i.e.: depending on the configuration, 60fps gets played at variable fps or audio gets de-sync from the very beginning).  
Can't log everything that happens right now, but will come back with a detailed rundown in a day, max (will try to record it as well!).

**Comment by zaps166** [comment]
> 60fps gets played at variable fps

Because QMPlay2 does frame skipping on the decoder if device is too slow to decode, so FPS can be variable.

I'm unable to play 60 FPS FullHD movie on HD5450 on QMPlay2 and Windows 10 default video player, so my graphics card is too slow. Your HD5850 is faster, but I wonder about UVD2.2 - maybe it has the same speed? How about playing *exactly* the same movie on native Windows 10 player? Is this video from youtube?

> audio gets de-sync from the very beginning

QMPlay2 can de-sync ~150ms if device is too slow to decode - it is OK in case of "variable" FPS.

> Can't log everything that happens right now, but will come back with a detailed rundown in a day, max (will try to record it as well!).

Ok!

**Comment by ktox** [comment]
[info.txt](https://github.com/zaps166/QMPlay2/files/1309373/info.txt)
> Can't log everything that happens right now, but will come back with a detailed rundown in a day, max (will try to record it as well!).

Sorry I couldn't keep my word, it took much longer than I estimated and I've been really busy with studies and work :(

I'll talk a bit more in detail down below, but my conclusion is: **IT WORKS**, period.   
Great work, zaps, especially with the frame skipping!

----

> Your HD5850 is faster, but I wonder about UVD2.2 - ***maybe it has the same speed?***

Bingo. Even though my 5850 can handle 1080p 60fps *gaming* with ease, for some reason it can't do it with DXVA2. After some testing, it seems the only things it can are: <=30fps up-to 1080p; 60 fps up-to 720p -- and only H264, not VP9 either, so FF/Chrome aren't HWAcc at all! (they were actually consuming up-to 30% CPU *just from the process rendering the YT video*)  
When I tried 1080p60, CPU usage skyrocketed to *at least* 20% in ffmpeg (even more in FF/Chrome!), yet DXVA2 lost frames all over the place, hardly reaching 50fps.

For anything other than 1080p60, like 1080p30 or 720p60, everything went smoothly, with no noticeable lag (also that FPS counter was a godsend for these tests!).

> QMPlay2 can de-sync ~150ms if device is too slow to decode - it is OK in case of "variable" FPS.

Indeed! DXVA2 alone had the least amount of CPU and RAM usage of all, and was the fastest of the DXVA2 alternatives as well-- but it always de-sync when it couldn't keep up with the target fps.  
On the other hand, DXVA2 with CPU memory was much better at handling sync issues, at the cost of lower fps and much more resources.

There's one thing I'd like to point out before I close this out though:  
While QMPlay2 used the *least* amount of CPU and RAM for YT content across all tests, I noticed ***a lot*** of RAM usage when it buffers long YT videos to a 100%.  
If you chose a 15+ min video, load it on QMPlay2 and left it alone "buffering" until the brackets reached the end of the line (100% video buffered), the amount of memory hogged would far exceed that of FF or Chrome.  
For example, for a 1080p60 15min video:  

Chrome (VP9, CPU) | QMPlay2 (H264, ffmpeg)
--- | ---
~400MB | 735MB (total) / 565MB (buffer)

Is this intended behaviour? Can it be changed in the Settings? Thanks :) 

------

With this post I attached my results file, where you can check out all this stuff I talked about, if you want (like that bit about the buffering).

I think that's all from me now. Thanks a lot, once again, for your dedication and patience in this regard, and for the amount of work you've placed in this great piece of software!  
Best of luck out there, and I hope I can be of help again in the near future!

El. Psy. Congroo.

**Comment by zaps166** [comment]
> While QMPlay2 used the least amount of CPU and RAM for YT content across all tests, I noticed a lot of RAM usage when it buffers long YT videos to a 100%.

RAM should be used, but not wasted. If RAM contains e.g. mem-leaks than it is bad, but when RAM contains buffered video which is used for fast seeking - it is OK (very large video could be stored on HDD cache, but QMPlay2 doesn't do this yet). You can adjust buffer in settings (also backward buffer), second tab (Playback settings).
I've noticed that my FF buffers only small chunk of video when it is paused.

> (seeking doesn't work)

It doesn't work only on DXVA2 or on all decoders or on every software?

---

You can benchmark DXVA2 using this: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.3.3-win64-static.zip

```
ffmpeg.exe -hwaccel dxva2 -i "input_file.mkv" -f null - -benchmark
```

You can replace `input_file.mkv` by full YouTube URL (copy first of two long URLs from QMPlay2 Information widget when playing)

You can give me the speed in "%".

**Comment by zaps166** [comment]
Btw. when you check QMPlay2 CPU usage - disable visualizations or just use Compact Mode (Alt+V) or Full Screen 😄

**Comment by ktox** [comment]
> RAM should be used, but not wasted.

That's a great philosophy, one I really like as well; especially in these times where "RAM is so cheap" that many devs simply spend it and completely disregard it.  
Unfortunately though, my main PC still has 4GB, so spending as much as 300 MB more just to buffer a YT video seems like a waste *for this machine and in this particular case, where I probably won't be seeking* -- that's why I asked if that behaviour could be modified in the Settings.

Please, don't think I'm generalizing here! I still consider this  
> when RAM contains buffered video which is used for fast seeking - it is OK

the correct decision here; even more so when you can manage it in the Settings.

Still worried about very long (30+ min) videos though -- does the ***Network buffer size (A/V packages count)*** amount of **50000** work as a default limiter?

---

> It doesn't work only on DXVA2 or on all decoders or on every software?

Discard that. Tried it again on lastest version with both ffmpeg and DXVA2, and it works perfectly.  
Also with even less CPU% than previously tested! (thanks to that Compact Mode tip 👍 ).  
I *might* test it again, just to be in the safe side, but for now there's no real reason to.

---

> You can benchmark DXVA2 using this  
You can give me the speed in "%".

Yes, of course. Will come back with results!  
Do you need this for something, though? Or is it like a tip of some sorts?
