### ISSUE TITLE
Would it be possible to add Qt 5 HDPI support like SMPlayer has?

### ISSUE THREAD

**Issue by stevenpusser** [zaps166/QMPlay2#168]
Pretty much the title has it all.

**Comment by zaps166** [comment]
QMPlay2 already supports HiDPI.

What OS do you use? It works for sure on Linux/X11, Windows and macOS.

**Comment by stevenpusser** [comment]
It's Debian Stretch's xfce 4.12.  Apparently xfce has no support for the QT 5 automatic hdpi framework; we'll have to wait for xfce 4.14 to fix that.  The buttons on qmplay2 and vlc get teeny-tiny as you go up to 4K, while qt5 SMPlayer is not affected.

**Comment by zaps166** [comment]
I can't force HiDPI mode on Linux, see #93.

Try:
`export QT_AUTO_SCREEN_SCALE_FACTOR=1`
or:
`export QT_SCALE_FACTOR=2`

You can create a script for launching QMPlay2 with these parameters. Or you can set it globally (e.g. in `/etc/profile.d/qt-hidpi.sh`), but setting it globally is not recommended, because most Qt5 apps doesn't support it properly (e.g. VirtualBox, Gwenview, Okular, etc.) and you'll have always pixelated images!
QMPlay2 supports HiDPI perfectly (I hope) :) I'm using it on Linux/X11, macOS and Windows and I have no problems + images (covers, video, icons, etc) are smooth. On macOS and Windows and some Linux environments QMPlay2 runs automatically in HiDPI mode when it should.
