### ISSUE TITLE
wayland ressource

### ISSUE THREAD

**Issue by mctdi** [zaps166/QMPlay2#214]
I started a session under wayland, under a old lenovo t450 (intel 5500).
QMPlay2 take more ressource under wayland then under xorg.

average of 35% instead of 20%
don't have this issue with mpv.

**Comment by zaps166** [comment]
Do you use OpenGL or QPainter for video display?

**Comment by zaps166** [comment]
If you use OpenGL, it runs in render to texture mode on Wayland. If you have visualizations, please go to options and set it also in OpenGL mode (don't forget click apply), otherwise CPU usage is huge.

**Comment by mctdi** [comment]
opengl

**Comment by zaps166** [comment]
> opengl

Ok, so please also check OpenGL in Visualizations (if enabled):

![screenshot_20181219_231529](https://user-images.githubusercontent.com/6239090/50251376-ff779f80-03e3-11e9-85ad-9e5f544899f3.png)

Otherwise it can be something wrong with Qt or other issue. Also please compare CPU usage on performace mode (`sudo cpupower frequency-set -g performance`).

If problem will still exist I'll check this on Wayland.

**Comment by mctdi** [comment]
OpenGL is enabled.
was already on performance

kde framework 5.52.0
qt 5.12

**Comment by zaps166** [comment]
I tried QMPlay2 on Weston a few moths ago and I notices that Qt apps works horrible there. I don't know how it works under KF5. If problem also exists with disabled visualizations (they should be disabled on fullscreen automatically if everything is working OK) on fullscreen OpenGL playback there is nothing I can do... How about other Qt apps ?
