### ISSUE TITLE
Youtube search not working

### ISSUE THREAD

**Issue by rahulgr8888** [zaps166/QMPlay2#3]
Its just showing one result of devicesupport
![screenshot from 2015-05-08 15 48 25](https://cloud.githubusercontent.com/assets/1639945/7534635/06c481ce-f59a-11e4-841c-11c380868172.png)

It was working fine around a week ago.
I'm on Ubuntu 14.04 and have installed youtube-dl too.

The video says- YouTube is upgrading to a newer version, which is not supported by this device or app.

**Comment by zaps166** [comment]
Yes, I know: https://github.com/zaps166/QMPlay2/wiki
But when I tried API v3, the Google shows me: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup." - I don't have an application key, so I must probably to register QMPlay2 in Google and I don't want to do it. I must find how to do this in other and simple way. You can still play Youtube by pasting URL from web page (Ctrl+U, choose YouTube).
I will try to do something with this later.

**Comment by rahulgr8888** [comment]
alright.. thanks for the app though! I've been using it for months now.
I'll also look into it, though I don't know much about QT development, but I'll look into alternate ways too.
Can't we do web scraping here though?

**Comment by zaps166** [comment]
I can try "https://www.youtube.com/results?search_query=something" like I done many years ago, but the page is changing, so I must update it quite often.
The simplest way is using GData API, e.g. "https://developers.google.com/youtube/v3/docs/search/list", but this doesn't work without key: https://www.googleapis.com/youtube/v3/search?part=snippet&q=something
I must rewrite Prostopleer and Youtube module, integrate it and maybe add more audio/video services. I must also rewrite video/audio in QMPlay2, because youtube has got video and audio in separate streams (if you want better audio/video quality e.g. 1080p 60fps).

**Comment by zaps166** [comment]
Fixed: https://github.com/zaps166/QMPlay2/commit/668ac480ad79092de3b71cdee6f44145b75757ea
Please test it, and if something doesn't work - reopen the issue.
