### ISSUE TITLE
Feature request: Twitch support

### ISSUE THREAD

**Issue by danrobi11** [zaps166/QMPlay2#408]
Twitch support would be nice. youtube-dl support twitch.

**Comment by zaps166** [comment]
What exactly do you want? If you paste URL as `youtube-dl` it should play.

**Comment by danrobi11** [comment]
I dont know how you're playing URL address. Me the only way that I know is CTRL+U and that doesnt wotk with Twitch.

**Comment by zaps166** [comment]
Ctrl+U and choose `youtube-dl`.

**Comment by zaps166** [comment]
Now it should be auto detected :) But I noticed not all stream working properly (looks like youtube-dl issue).

**Comment by danrobi11** [comment]
> Ctrl+U and choose youtube-dl

Nice I never noticed there was a drop down grid menu there

> But I noticed not all stream working properly

Ya, Twitch stream here doesnt render the video only audio :/

> looks like youtube-dl issue

No. I always install [youtube-dl latest release](https://github.com/ytdl-org/youtube-dl/). MPV doesnt have any issue playing Twitch. Therefore not a youtube-dl issue.

**Comment by zaps166** [comment]
> I always install youtube-dl latest release

QMPlay2 downloads it automatically on first use after software start. It doesn't use system-wide `youtube-dl`.

> Ya, Twitch stream here doesnt render the video only audio :/
> Therefore not a youtube-dl issue.

![Screenshot_20210406_183136](https://user-images.githubusercontent.com/6239090/113746248-65e47100-9706-11eb-86db-5020b05e42e5.png)

This is a youtube-dl issue, because I have the same from command line: `youtube-dl <link>`. If video playes, I have sound and video, but after a few seconds video stops.

I don't have any problems when I paste HLS URL from Video DownloadHelper from Firefox, so IMHO youtube-dl issue :smile: Web browser can generate better URL.

> Suggestion: CTRL+Q to Quit instead of ALT+F4.

Why? Ctrl+Q is annoying in apps, because I close them quite often when I want Ctrl+A and I press a wrong key :/

**Comment by danrobi11** [comment]
Ya the commercial break does work here too, but soon as the commercial break ends screen goes dark.
