### ISSUE TITLE
Add M3U8 Download Support

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#413]
Currently the downloader doesn’t support streams in M3U8 playlist.

**Comment by zaps166** [comment]
Could you give me an URL for testing?
I use QMPlay2 for downloading M3U8 HLS streams sometimes.

**Comment by zo-shin** [comment]
http://1111296894.rsc.cdn77.org/ls-54548-1/tracks-v1a1/mono.m3u8

**Comment by zo-shin** [comment]
There are a lot on radio-browser site.

**Comment by zaps166** [comment]
![Screenshot_20210420_193828](https://user-images.githubusercontent.com/6239090/115440416-fe531900-a20f-11eb-8ea5-5f44815f919d.png)

Works properly (Linux from git and Windows).

**Comment by zo-shin** [comment]
I tested recent versions on three computers running Windows XP and Windows 7, and found:
1 - **v19.12.19** is the last version supporting all the M3U8 streams download.
2 - Since **v20.05.02**, for some M3U8 streams, like the one provided, I always get the **download error** notification.
3 - **v20.12.07** is an exception among them, which downloads all the M3U8 streams well.
Another suggestion: a record button can be added for the convenience.

**Comment by zaps166** [comment]
Oops, sorry, the issue is about download, not playback.

**Comment by zaps166** [comment]
> 1 - v19.12.19 is the last version supporting all the M3U8 streams download.
2 - Since v20.05.02, for some M3U8 streams, like the one provided, I always get the download error notification.
3 - v20.12.07 is an exception among them, which downloads all the M3U8 streams well.

Depends on FFmpeg version, error is: `Application provided invalid, non monotonically increasing dts to muxer in stream 1: 147 >= 15`. Previous FFmpeg versions had warning, now it is an error.

**Comment by zaps166** [comment]
Fixed, but it depends also on stream, YouTube live m3u8 streams was downloaded properly.
