### ISSUE TITLE
Search does not work on Haiku 64bit nightly

### ISSUE THREAD

**Issue by Brunobasta** [zaps166/QMPlay2#426]
Search was working before. Now the search result window is empty.
However my Files on History play well.
I reported to Haiku Depot Server, but they send me to you.
It is not a Haiku problem!

**Comment by DarkWav** [comment]
> Search was working before. Now the search result window is empty.
> However my Files on History play well.
> I reported to Haiku Depot Server, but they send me to you.
> It is not a Haiku problem!

The problem is that the Haiku maintainers only provide stable release versions of QMPlay2 (e.g. 21.03.09) in their repository and don't backport all bugfix patches that got added to the master branch later on in development.

The [patch that's required to fix YouTube Search in Version 21.03.09](https://build.opensuse.org/package/view_file/multimedia:apps/QMPlay2/0001-fix-youtube-search.patch?expand=1) is probably not applied by the haiku maintainers yet, hence the issue persists. To be fair, it isn't even incorporated into the official AUR version yet, but the qmplay2-git package exists there which has the fix.

You best bet is to compile the latest QMPlay2 master from source. Alternatively, you may also add YouTube URLs manually to your playlist.

**Comment by zaps166** [comment]
Duplicate #425
