### ISSUE TITLE
Adding Sharpness Control feature to video equalizer, Windows10 OS.

### ISSUE THREAD

**Issue by elegey** [zaps166/QMPlay2#45]
I would like to learn how to add the sharpness control feature to video equalizer. And possibly adding other features as well. 

Thanks for your help.

**Comment by zaps166** [comment]
Windows 10 is Windows just like XP - it uses OpenGL for video displaying (as primary and best video output), so it is the same also on any other OS. If you want to do it, the simplest method is to use Linux, because you must compile everything (on Linux it is very simple).

You must add a new sharpness slider, add a feature to OpenGL2 module to control it and send sharpness level to GLSL and you must write a fragment shader in GLSL for it.

You must know C++, Qt, how it works in QMPlay2, GLSL and you must be able to compile QMPlay2 for Windows (with dependencies). And the most important thing - you must know how to write a sharpness filter (also to achieve best performance) :)

I think I can do this, but later.

**Comment by elegey** [comment]
Thanks for your answer. I must say that I will wait for you to do it. It
seems that there are a few steps that I am not familiar with. It is an
excellent Player.



On Sun, Jul 10, 2016 at 11:20 AM, Błażej Szczygieł <notifications@github.com

**Comment by zaps166** [comment]
Hmm, is *sharpness* really a video equalizer? It is an image filter which also uses neighbour pixels to calculate the output pixel... I can add it to video equalizer, but maybe this menu should change its name (video adjustment or just basic filters, effects)?

**Comment by elegey** [comment]
Thanks for your information. I would say, and I agree with you that the
sharpness control should belong to the video adjustment menu, under basic
filters.



On Mon, Jul 11, 2016 at 10:46 AM, Błażej Szczygieł <notifications@github.com

**Comment by zaps166** [comment]
Sharpness added to OpenGL2 module. Now it needs GUI modification (add slider, etc.): ca2d6cf358c614d9ec6a48a15a981027025d8a76

**Comment by zaps166** [comment]
Done: ca2d6cf358c614d9ec6a48a15a981027025d8a76, a3016d0faaab6198b6acfef18031e297fde4e843 :)

**Comment by elegey** [comment]
Thanks for the great work, Now, how do I implement these modifications into the Player?  I am not familiar regarding this subject. Any help will be much welcomed.

**Comment by elegey** [comment]
Thank you.

**Comment by elegey** [comment]
Now, how do I implement these changes into the Player. I am using Windows 10 Pro. Thanks for the great modification.

**Comment by zaps166** [comment]
If you are not able to compile it under Windows, you must wait for next QMPlay2 release. At least I can build current version from git and send EXE installer via email.

**Comment by elegey** [comment]
Thanks, Yes. please do build the current version from GIT and send me the
EXE installer via email,. Thank you in advance for the great help.

**Comment by zaps166** [comment]
My email is visible on github, so write me an email (I don't know your email). Which version: 64 bit or 32 bit?
