### ISSUE TITLE
why qmplay2 become default file manager in steam linux?

### ISSUE THREAD

**Issue by realsifocopypaste333** [zaps166/QMPlay2#517]
when i try to open file manager in steam apps in linux, why it open with qmplay2, not the default file mager like thunar / pcmanfm ,caja etc ?

when i uninstall qmplay2 it become normal , it open caja/thunar/ pcmanfm .

thanks

**Comment by zaps166** [comment]
Because QMPlay2 opens `inode/directory`, look [here](https://github.com/zaps166/QMPlay2/blob/dd0e1d274a956a98dab462335fafe62eedfc669d/src/gui/Unix/QMPlay2.desktop#L12).

The same is in Kaffeine, RawTherapee, Gwenview, Kate, ... I don't know why your DE set QMPlay2 as default.
What DE do you have? Go to settings and change default file browser.
Screenshot for MATE settings:
![Screenshot_20220726_174627](https://user-images.githubusercontent.com/6239090/181051047-d1258917-77ca-46cc-a481-e318f0730643.png)
