### ISSUE TITLE
Streamlink

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#535]
Hello, tahnk you for this awsome media player 🥇 it will be even more great to add support for the famous CLI "streamlink" to play even more videos from more web sites if yt-dlp fails, because using command line especially to choose video quality is a bit difficult and complex, thanks a lot!

https://streamlink.github.io/

**Comment by zaps166** [comment]
Hi!

Try

```sh
streamlink -p QMPlay2 --player-http URL best
```

or

```sh
streamlink -p QMPlay2 -a /dev/stdin URL best
```

I don't know why the named pipe isn't working, however both above commands works.

**Comment by zaps166** [comment]
For the worst quality just replace `best` for `worst`.
480p and 360p are common qualities, so maybe they will be available, too (put `480p` or `360p` instead of `best`).

---

To see all available qualities, just run:

```sh
streamlink URL
````

It will output possible qualities for URL.

---

Try both of two commands I gave you in my previous message and choose what is working better.

**Comment by trimechee** [comment]
Hello, i find these software, may be this can help to have native integration with media player wihtout the need of command line....


https://streamlink.github.io/thirdparty.html

https://github.com/back-to/liveproxy

https://github.com/back-to/generic

**Comment by parkerlreed** [comment]
yt-dlp handles streaming and its already a part of QMPLay2. What do streamlink or the others provide that yt-dlp doesn't cover?

**Comment by trimechee** [comment]
Streamlink is focused on live streams, from exemple streamlin can play many live streams from offcial websites of tv channels, yt-dlo is focused on vod streams, video on demand videos....
