### ISSUE TITLE
Paste url adress from clipboard button

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#540]
Hello, I copied the url address of a youtube video, then I tried to paste the address in QMPlay2, but I have to click several times before I can paste the url address and play the video, it will be great to simplify the process and make it faster by adding either a button or a widget visible and anchored in the main interface: "paste url adress from clipboard" or add keyboard shortcut to past and automatically open the adress url from the clipboard, thank you so much!

**Comment by zaps166** [comment]
Hi, you can Ctrl+V on playlist or press Ctrl+U and Enter.

**Comment by blzos** [comment]
> My wish is that QMPlayer2 plays the video directly without adding it to a queue in a playlist

Maybe add the Alt+V combination in the options (Set key bindings), "Play the URL from the clipboard immediately", without adding to the playlist (do not add to the playlist - for consideration, a controversial decision).

I installed the “paste” function on the V button (without Ctrl). QMplay will easily determine what kind of link it is, a direct address or a link to YouTube. However, the cursor is not placed on the inserted element (!), as happens if you use СTRL+U! (bug?) . The element is placed at the end of the list, you have to go to it and press the space bar to start playback.
In this case, you can use CTRL + U (can change it to the U button), set the “PLAY” option in the window, the address will already be inserted, all you have to do is press Enter. Both methods work but require unnecessary actions or open dialog boxes with unnecessary questions.

**It would be nice to simplify this. Alt+V paste and play. Simple and accessible.**

**Comment by zaps166** [comment]
@blzos Alt+V is used for compact view.

**Comment by zaps166** [comment]
Maybe Ctrl+Shift+V? It's known hotkey in terminals on Linux to paste text.

**Comment by zaps166** [comment]
Holding Shift selects multi items in playlist when pasting. I'll use Alt+Ctrl+V.

**Comment by zaps166** [comment]
> without adding to the playlist (do not add to the playlist - for consideration, a controversial decision)

I'm going to use existing functions which relies on playlist. Moreover I'd prefer adding it to playlist (for myself tho).

There's option which clears all ungroupped playlist entries on application quit (to cleanup such mess).

**Comment by blzos** [comment]
> Maybe Ctrl+Shift+V? It's known hotkey in terminals on Linux to paste text.
> _shortcuts->appendAction(playlist->pasteAndPlay, "KeyBindings/Playlist-paste-and-play", "Ctrl+Shift+V");_

Yes, that will be enough. If the user needs, he can change it to his own combination in the settings.

> Alt+V is used for compact view.

Right, I looked at this on the default clean version of the program. I changed these bindings on the working version.
_I don't like double keyboard shortcuts for simple operations that don't require attention._

![QM-CaptureStream5](https://github.com/zaps166/QMPlay2/assets/166966429/da451de5-f960-4117-bde7-bb01c44d54da)
