### ISSUE TITLE
Play/Pause when click

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#543]
Hello, it will be great for more simplicity and speed to add the option to pause or play the video when we click in the video, because it's a bit difficult to go digging in the bottom bar and aiming for the play/pause button to those who have vision problems, thank you very much :)

**Comment by parkerlreed** [comment]
Middle button already has the desired effect if you have that available

**Comment by blzos** [comment]
The video pause/play function can be assigned to the right mouse click (instead of the current menu)
[Settings] -> Playback settings -> Right mouse click:
Open player menu [current]
Play/Pause
Mute

But it would be good to implement the function of moving the window when you press and hold the left mouse button on the video (because holding the window title is not always convenient. Perhaps the Linux version has this, but in Windows you have to use the window title).

If you press control and move the mouse with the left mouse button pressed, the "Volume" text will move (if you activate it) Bug or feature? (Windows 10)

**Comment by blzos** [comment]
> I can't find the option

I offered to the author how this could be implemented, we are waiting for his response and new features in the next version of the player. To make QMplay2 more user friendly.  At the moment, the right button does not provide useful functionality.

**Comment by zaps166** [comment]
> If you press control and move the mouse with the left mouse button pressed, the "Volume" text will move (if you activate it) Bug or feature? (Windows 10)

Feature. You can move subtitles with control. press "R" to reset. With Shift + click you can move video.

> [Settings] -> Playback settings -> Right mouse click: [enhancement!]

Good idea, but it's UI/UX enhancement. This feature is already in QMPlay2 since 5f2ac1f18e69c5c96789a45ce67b2d73c8e8218d (7 years!).

---

I hate XML (QtDesigner) Ui file. Modifying it is pain, much better with C++. Idk why I wanted to convert C++ to this XML thing. Now I'm not motivated to touch settings. Anyway, settings need filter bar :smile:

**Comment by zaps166** [comment]
@trimechee Sorry I didn't replied earlier that this feature is in QMPlay2 for years.

**Comment by blzos** [comment]
Yes it works:

[Options] > [Settings] > [Playback settings] > Primary mouse button on video dock toggles playback > Enabled

or 

QMPlay2.ini
Change parametr:
LeftMouseTogglePlay=1
