### ISSUE TITLE
are youtube videos saved using youtube-dl

### ISSUE THREAD

**Issue by sant527** [zaps166/QMPlay2#57]
When i open a video from youtube, is youtube-dl saving the video somewhere.

So that i can see tha video again without internet

**Comment by zaps166** [comment]
> is youtube-dl saving the video somewhere

No, `youtube-dl` only extracts stream URL(s) for QMPlay2. Some YouTube video works without it.

---

You can download YouTube video via QMPlay2, but it is not yet recommended, because it can download only 720p with AAC audio (right-click on video in YouTube browser and click "Download" or in playlist, right click, "Extensions->Download").

You can download better quality, but you must manually download audio and video separately (expand tree in YouTube browser) and then merge them e.g. via [mkvtoolnix](https://mkvtoolnix.download/).
You can also use `youtube-dl` from command line, so if you also have `ffmpeg` command line tool, it will automatically download and merge them.

Downloading will be improved in the future.

**Comment by zaps166** [comment]
Closing, because this is a question. Please check for updates, because downloading will be improved in the future :)
