### ISSUE TITLE
[FR]: Add FILE delete option

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#575]
I usually delete unwanted media files while/after playing them. That's possible from some players QMMP (if you enable it), Audacious and some audio tag editors.

Please, could you add this feature to QMPlay2? With that feature, I can forget definitively any other video/audio player. In fact, I was looking a faster player. QMPlay2 opens/closes itself instantly when launching to play any media file, while SMplayer takes about 4 seconds to do same thing.

![image](https://user-images.githubusercontent.com/13048959/210184154-f59dda6c-2ee2-4af4-9410-2b409b5aa2cb.png)

**Comment by zaps166** [comment]
Good idea, but dangerous (deletes files) - it must be disabled by default.

**Comment by RafaelLinux** [comment]
Of course. That's the way it's implemented in QMMP or Audacious. User must enable it and after enabled, it's clear in menu that is delete FILE not a playlist entry  ;)

**Comment by blzos** [comment]
> Good idea, but dangerous

For example, for Windows this is not critical, since the files are deleted to the Recycle. However, given the multi-platform nature of the player, there are some nuances. For example, in Linux you can use the ~/.local/share/Trash/ folder for this. However, there is no such option on Android.

This part of the menu needs to be reorganized a little, since it is currently redundant with unnecessary functions. In particular, "Remove entries without groups" makes the menu too wide. The menu item "Remove selected entries" should also be shortened, since if the elements are not selected, nothing will be deleted.

Add a "Delete to Trash" checkbox to the settings and if it is activated by pressing Shift+Del, let the user delete the file to the Trash. At the same time, clearing the list (Clear list) is also a controversial function, since it repeats the action of Ctrl+A and the Del key. In this case, it is needed once a year =) "Remove entries without groups" once every two years.

I sketched out a small sketch of what it might look like:

![QM-CaptureStream3](https://github.com/zaps166/QMPlay2/assets/166966429/7d9da47e-7323-455f-b2bd-db749563bf53)

Thank you for your work!
