### ISSUE TITLE
Vulkan :: Discarding "llvmpipe (LLVM 13.0.0, 256 bits)", because:  - Not a GPU

### ISSUE THREAD

**Issue by 0pLuS0** [zaps166/QMPlay2#579]
Hello,

Using Vulkan as the Renderer when I start QMPlay2 I get this output at the term;

```Vulkan :: Discarding "llvmpipe (LLVM 13.0.0, 256 bits)", because:  - Not a GPU```

What does this mean?

THANKS

**Comment by zaps166** [comment]
Hi,

llvmpipe (lavapipe) is a CPU Vulkan implementation (doesn't use graphics card). QMPlay2 discards it, because it's very slow. It's better to use OpenGL when Vulkan is not supported (or drivers not installed) by GPU than using CPU's Vulkan implementation. Also QPainter output should be faster (but is very limited) if you want to use only CPU.

You can uninstall it (on Arch Linux it's a `vulkan-swrast` package), it's useless for 99.9% applications.

---

QMPlay2 allows to use it by `QMPLAY2_ALLOW_VULKAN_CPU=1` environment variable.

**Comment by zaps166** [comment]
> So for normal Nvidia usage, go with OpenGL and XVideo?

XVideo is obsolete, it's for 15-20 years old clunkers :smile:
OpenGL has less features in QMPlay2 than Vulkan, so use Vulkan (the default setting). However on RTX + Linux + Vulkan - CUVID doesn't work properly on QMPlay2 so far.

`Vulkan :: Discarding "llvmpipe (LLVM 13.0.0, 256 bits)", because:  - Not a GPU` - ignore this, just a log.

**Comment by 0pLuS0** [comment]
Ok on XVideo...

And I was talking about the; ```Legacy video output priority``` for XVideo, so I'll place it then on QPainter.

I'm using all the Render settings for Vulkan is that good?

THANKS

![qmplay2](https://user-images.githubusercontent.com/36190223/212797424-2f0d1a49-ce81-4df4-9acc-d865c1f09c45.jpg)
