### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by lnxfsf** [zaps166/QMPlay2#588]
[youtube] z5hpV16nxts: Unable to extract uploader id;

I get this error, when opening some videos. It doesn't load.

I'm on latest version: QMPlay2 23.02.05

Using AppImage on Linux

**Comment by mjb10** [comment]
Same problem either on latest version of qmplay2 or previous. If the alert message is correct seems like a yt-dlp package error. I've updated yt-dlp manually compiling their AUR repo but still the same issue.

**Comment by zaps166** [comment]
Can you check if yt-dlp can download video from command line? Or give me URL to the video.

**Comment by zaps166** [comment]
`~/.config/qmplay2` - should be there

**Comment by mjb10** [comment]
This issue is solved by updating yt-dlp. These are the steps I followed in order to do so:

**1. Download and compile/install yt-dlp-git from AUR.** ( Link: https://aur.archlinux.org/packages/yt-dlp-git )
**2. Go to the generated bin file located on '/usr/bin/yt-dlp'.**
**3. Overwrite the file located on '~/.config/qmplay2/yt-dlp' with file in step 2.**

That's all.

**Comment by zaps166** [comment]
I see, I just tested now and it really stopped working. Use mjb10 temporary solution until they release compiled package (QMPlay2 will automatically update in this case).
