### ISSUE TITLE
"Download and convert" fails (mp3 and ogg)

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#646]
This error doesn't happen with option "Download", only when trying to convert ("MP3 224k" or "OGG container" options).
I don't know if it happens with all MediaBrowser files, but all I checked, fails with same error (in console):
`Downloader: Can't convert, because source and destination path is the same: /home/usuario/Music/Pendiente/filename.mp3`

In QMPlay2 interface, after download, show "Conversion error", and click on "Retry" button finish with same error.

Please, if you need more info, let me know.

Linux openSUSE Tumbleweed.

[borrar_registro_QMPlay2.txt](https://github.com/zaps166/QMPlay2/files/12332814/borrar_registro_QMPlay2.txt)

**Comment by zaps166** [comment]
You can't pack MP3 codec into OGG container. QMPlay2 doesn't convert to OGG, it's just repacking the data into another container. It's for YouTube. It has WebM with OPUS codec which can be packed into OGG container.

For MP3 it's a conversion, but it's pointless to convert MP3's from MediaBrowser's MyFreeMP3 to MP3 (you'll just do the [generation loss](https://en.wikipedia.org/wiki/Generation_loss))...
The error is probably because you have the same source and destination file (the same directory and the same file suffix): `Downloader: Can't convert, because source and destination path is the same`.

**Comment by RafaelLinux** [comment]
I understand but, if that menu is only functional for YouTube, is not better to disable those functions when en MediaBrowser?

**Comment by RafaelLinux** [comment]
Ok. I didn't notice the "+" button!!! It's interesting. I'll try my own "profiles" but think about changing menu for users with no skills that will try what I commented and will not work .... ;)

Thank you

**Comment by zaps166** [comment]
> I'll try my own "profiles" but think about changing menu for users with no skills that will try what I commented and will not work .... ;)

You mean too hard to write an FFmpeg command?

**Comment by RafaelLinux** [comment]
In fact, `ffmpeg` is so complex as awk!!! Anyway, I was talking about "users" not "CLI masters". Luckily, there exist some `ffmepg` GUI frontends to get the final CLI `ffmpeg` command.
