### ISSUE TITLE
QMPlay2 crashed

### ISSUE THREAD

**Issue by Dominiquini** [zaps166/QMPlay2#667]
Unable to start QMPlay2 on Windows!
I downloaded the portable version for Windows ( QMPlay2-Win64-23.10.22-portable.7z ), but it don't start!

[QMPlay2.log](https://github.com/zaps166/QMPlay2/files/13201465/QMPlay2.log)

OS: Windows 10 x64

Thanks

**Comment by Dominiquini** [comment]
> As first, could you check if [this](https://vulkan.gpuinfo.org/downloads/vulkancapsviewer_3.32_win64.zip) runs or crashes?

It's crashing too! [Report.wer.txt](https://github.com/zaps166/QMPlay2/files/13206244/Report.wer.txt)

But all other video players that I have installed works fine here!
I also tested here this program that maybe is related with that you send me (https://www.geeks3d.com/20220802/gpu-caps-viewer-1-56-released/) and it works too!

Thanks.

**Comment by zaps166** [comment]
> It's crashing too! [Report.wer.txt](https://github.com/zaps166/QMPlay2/files/13206244/Report.wer.txt)

The problem is with your GPU Vulkan driver somewhere. Do you have Intel+Nvidia hybrid setup? Please just reinstall/update all GPU drivers. I know this issue, it's rare, reinstalling/updating drivers helps.

---

In the future I can try to avoid this crash by checking it separately and display a message to the user, but driver reinstall will still be necessary to run it properly.

**Comment by Dominiquini** [comment]
I opened a bug on that program and maybe I was able to resolve it: https://github.com/SaschaWillems/VulkanCapsViewer/issues/193

I'll test this program again soon!

Thanks.

**Comment by Dominiquini** [comment]
It's working now! The program "AgaueEye" installed on my system was interfering here. As soon I uninstalled, everything starts working!

Thanks.

**Comment by zaps166** [comment]
Right, I forgot about additional layers, too :smile: Good it's working now!
