### ISSUE TITLE
Hello friend, the YouTube playlist link won't play! 

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#719]
Hello friend, the YouTube playlist Video link won't play! 

``
https://www.youtube.com/watch?v=OypBL4GRBMQ&list=PLf7KCRuAw-wjm7cj8w1ZWp1M6eyNR048b&index=26
``

Windows 10 19044
[QMPlay2 24.04.07](https://github.com/zaps166/QMPlay2/releases/tag/24.04.07)

**Comment by zhouxinghong** [comment]
If you can't play it either, then I guess most of the Youtube playlist videos won't play. The strange thing is that I can play it successfully with VLC.

**Comment by blzos** [comment]
This has already been added to the list of improvements: https://github.com/zaps166/QMPlay2/issues/606

If we draw the team's conclusion: yt-dlp.exe -g youtube-link_**withplaylist**
_sample: https://www.youtube.com/watch?v=OypBL4GRBMQ&list=PLf7KCRuAw-wjm7cj8w1ZWp1M6eyNR048b&index=26_
we get:
Video link
Audio link
And some error:
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

This data can be seen in the link: &**list**=PLf7KCRuAw-wjm7cj8w1ZWp1M6eyNR048b&**index**=26_

### Link does not open!


If we draw the team's conclusion yt-dlp.exe -g youtube_link_**withoutplaylist**
https://www.youtube.com/watch?v=OypBL4GRBM
we get:
Video link
Audio link

### Link opens!

I can assume that the output of the yt-dlp command is processed incorrectly (withplaylist) due to the fact that after the links to the streams there is some text data that the player is trying to “chew”
