### ISSUE TITLE
No AppImage?

### ISSUE THREAD

**Issue by ArchieA** [zaps166/QMPlay2#726]
There's no AppImage for Linux 64-bit on Assets. Is there any chance you can bring it back? Thanks.

**Comment by zaps166** [comment]
My build environment is too old. I'll upload AppImage or tar.zst archive later.

**Comment by ArchieA** [comment]
Understood. Thanks.

**Comment by leirbag28** [comment]
@zaps166 What do you mean your build environment is too old???  I hope you don't mean you will stop supporting Ubuntu 16.04 and 18.04...because this is The BEST thing about QMPlay2.Appimage is that it is one of the ONLY apps on Linux that is built properly as a UNIVERSAL Appimage.

**Comment by leirbag28** [comment]
QT6 is probably not a good idea as it probably wont work on Ubuntu 18.04 which is what I use. I already have not been able to use the Youtube feature because Inwoulf have to upgrade Python3 which will break my other Python apps.QMPlay2 is super awesome…one of the only apps that can loop video perfectly and let me play video clips back to back sequentially sonthat I can VJ, Do presentaions which can have pictures inbetween. Thank You! Only wish I could change the fonts in the interface (which i thought inhad done once in an older version.Sent from my iPhoneOn May 29, 2024, at 5:39 PM, Błażej Szczygieł ***@***.***> wrote:﻿
I just need C++17 library there. As long as glibc is not touched, it'll be compatible. But I don't know if I can use Qt6 in this case, hmm.

**Comment by zaps166** [comment]
You're talking about Ubuntu 18.04 here, so maybe drop 16.04?

> QT6 is probably not a good idea as it probably wont work on Ubuntu 18.04

Qt 5.15.2 doesn't work on 16.04, I patched it (one function call). Maybe something simple could be done with Qt6, too?

**Comment by leirbag28** [comment]
I would not say to drop Ubuntu 16.04 because if I am not mistaken, using Ubuntu 16.04 or CentOS is the proper way to build a universal Appimage. (However, if it needs to be dropped for some reason, then I suppose yes as long as Ubuntu 18.04 and above are supported).Sent from my iPhoneOn May 30, 2024, at 4:56 AM, Błażej Szczygieł ***@***.***> wrote:﻿
You're talking about Ubuntu 18.04 here, so maybe drop 16.04?

QT6 is probably not a good idea as it probably wont work on Ubuntu 18.04

Qt 5.15.2 doesn't work on 16.04, I patched it (one function call). Maybe something simple could be done with Qt6, too?

**Comment by zaps166** [comment]
Ok, I'll keep compatibility with Ubuntu 16.04.

**Comment by leirbag28** [comment]
Awesome!Sent from my iPhoneOn Jun 4, 2024, at 5:58 PM, Błażej Szczygieł ***@***.***> wrote:﻿
Ok, I'll keep compatibility with Ubuntu 16.04.

**Comment by zaps166** [comment]
Done (added to 24.05.23 release)!

**Comment by zaps166** [comment]
> Qt 5.15.2 doesn't work on 16.04, I patched it (one function call).

Or it was for Suse 13.1..? Don't remember, but I still use this patch.

**Comment by leirbag28** [comment]
I saw! Just tested it and its working. Video Playback and Internet radio stations is what I testedSent from my iPhoneOn Jun 5, 2024, at 12:24 PM, Błażej Szczygieł ***@***.***> wrote:﻿
Done (added to 24.05.23 release)!
