### ISSUE TITLE
Instructions to compile on AARCH64

### ISSUE THREAD

**Issue by defencedog** [zaps166/QMPlay2#765]
Please dont forget growing numbers og RaspberryPi, OrangePi & RADAXA users. Any prebuilt package or compile instructions?

**Comment by zaps166** [comment]
Look here: https://github.com/zaps166/QMPlay2?tab=readme-ov-file#installation-from-sources

You can build it from sources for Flatpak or from AUR (Arch Linux and it's derivetives, also on AARCH64). Alternatively you can build and install it manually from sources. All required info in linked README.

Never tried Flatpak on ARM, but compilation instructions are the same for x86-64 and AARCH64 and other architectures.

Clone GIT repository and initialize+update submodules (see README) or download source code from [releases](https://github.com/zaps166/QMPlay2/releases). Note: use ` QMPlay2-src-*.tar.* ` file instead of Source code prepared by GitHub, because it doesn't contain submodules!
