### ISSUE TITLE
[Feature request] more than 1 tab with playlist

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#77]
I could use more than 1 tab with different playlists. Proszę o dodatkową zakładke/zakładki (z mozliwościa zmiany nazwy) z playlistami. Np w jednej radia internetowe w kilku folderach, w drugiej kilka folderów z muzyką z dysku lokalnego, 3cia filmy na przykład. Internet Radios zakładka nie jest edytowalna niestety, trudno cos znaleźć w natłoku stacji, dodać jeszcze trudniej, drag&drop nie działa...

**Comment by zaps166** [comment]
I'll think about this, generally playlist will be improved.
Currently you can use tree (as I do) for movies, music, etc - this was my idea more than 6 years ago :)

**Comment by zaps166** [comment]
`Internet Radios` - dlaczego miałaby być edytowalna? Można poprawić angielskie tłumaczenie.
Drag and drop nie ma, bo nie wiem jakie zastosowanie miałoby mieć - można kliknać 2x albo wcisnąć enter.

> dodać jeszcze trudniej

Klikasz na 'dodaj nową stację radiową', wpisujesz nazwę i adres - myślałem, że to łatwe :)

---

Poza tym `Internet Radios` to nie playlista (osobny issue) i musi być kiedyś napisane od nowa.

**Comment by Amaunator** [comment]
Edycja by się przydała by usunąć te których się nie słucha albo chociaż schować. Trudno znaleźć to czego się słucha . Drag&drop by się przydało by *.pls czy *.m3u przeciągnąć a nie szukać adresu strumienia. Moje kroki jeżeli bym chciał użyć tej zakładki to ściągnięcie playlisty, otwarcie w edytorze, kopiowanie adresu, wklejenie do formy. A dało by się dodać miniaturkę JPG loga stacji jak w przypadku polskiej stacji? Wiem że się czepiam detali :) Ogólnie wielkie dzięki za dotychczasowe zmiany!

**Comment by zaps166** [comment]
> Edycja by się przydała by usunąć te których się nie słucha albo chociaż schować.

A no to tak. Ja myślałem, że chodzi o sam napis na tej karcie `Internet Radios`, że ba być edytowalny :smile: Źle zrozumiałem :)

> Drag&drop by się przydało by *.pls czy *.m3u przeciągnąć a nie szukać adresu strumienia.

Teraz to ma sens, czyli przeciągasz playlistę z pliku do stacji radiowych i on sam dodaje.

---

Radia to osobny issue (radios are a separate issue), więc możesz po prostu założyć nowy i dodać pomysły :)

---

About this issue:
- playlist widget will be improved in the future, especially better disk synchro and maybe simple library (#11),
- the idea is to use groups/folders instead of tabs, because this is a tree playlist. You can create `Movies` group and then you can create subgroups. The same with radios, e.g. `Radios` and inside `Pop`, `News`, `Anime`, etc :)

**Comment by Amaunator** [comment]
In my playlist I have 3 folders with radios that I want to keep there for good. I add folders with music, films as I go. When I finish I delete them from playlist.  Don't want by accident to delete folders with radios. Any chance to introduce ability to lock folders, items in place/ unlock them? Maybe to save playlist?

**Comment by zaps166** [comment]
lock/unlock items - this is a good idea to me :) I'll try to do it for the next release.

> Maybe to save playlist?

What do you mean? You can save playlist/gropy from popup menu. Also playlist is saved in `~/.qmplay2` while closing. If you accidentally remove something, you can kill QMPlay2, then it'll not be saved :smile:

**Comment by zaps166** [comment]
Locking items - DONE (089ad2ed9b232664b15a7f6cc323f38c6bfa79ef) :) Currently no plans for more than one tab with playlist...
