### ISSUE TITLE
Inconsistent playback of a specific video with missing frames

### ISSUE THREAD

**Issue by Realex-fire** [zaps166/QMPlay2#812]
Hello @zaps166,
Such videos are played inconsistently (sometimes faster, sometimes slower). A sample from the Internet:
```
ffmpeg -i https://samples.mplayerhq.hu/V-codecs/WVP2/PhotoStory3.wmv -vf mpdecimate -vsync vfr output.mp4
```
Try to play `output.mp4` using QMPlay2 and FFplay. FFplay does it better.

Could you please check this?
Thank you.

**Comment by zaps166** [comment]
Confirmed

**Comment by zaps166** [comment]
Something is wrong with video playback

**Comment by zaps166** [comment]
Caused by: f78fae7fa4fa48f556dd0e976e4dd6d01bc014cb

Maybe I should adjust it, but if I remove it, something else can be wrong.

**Comment by zaps166** [comment]
What if it will take on hour because of corrupted stream?

**Comment by zaps166** [comment]
Do you have any real videos like this?

**Comment by zaps166** [comment]
Is it OK to set it to 5 seconds? Or you have other videos where it will not work?

**Comment by zaps166** [comment]
> Maybe https://github.com/zaps166/QMPlay2/issues/614#issuecomment-1581983426 stream?

It's playing now. Let's forget about it :sweat_smile:

**Comment by zaps166** [comment]
For me this file is corrupted - no need to do anything, just press `O` to disable corrupted video playback, so you'll be able to seek (QMPlay2 playback position is taken from video if exists).

> the amount of video memory used increases after the first repeat. For testing I use H.264 video. This does not happen on other decoders.

This is maybe a bug.

**Comment by zaps166** [comment]
> OK, if you think that automatic switching is not necessary.

"Fixed"

**Comment by zaps166** [comment]
> and VkVideo is still experimental

VkVideo has issues because of horrible Intel drivers and poor AMD drivers (idk about Nvidia - should be good). I think FFmpeg has correct implementation, QMPlay2 implementation isn't that bad, too.

> Btw. OpenGL+DXVA2 looks like the best combination for Windows, since D3D11VA has a zero copy only for Intel and does not always work

OpenGL+DXVA2 is **not** zero-copy either.

---

Zero-copy HW decoders in QMPlay2 (if driver is zero-copy and you didn't trigger HQ downscale mode):

- VkVideo
- VA-API
- VideoToolBox
- D3D11VA for Intel when experimental checkbox is checked (not recommended)

Non zero-copy HW decoders in QMPlay2:
- DXVA2
- D3D11VA
- CUVID

**Comment by zaps166** [comment]
> Hm... For me, DXVA2 and VkVideo use the same amount of video memory.

OpenGL + DXVA2 [does a copy](https://github.com/zaps166/QMPlay2/blob/615cd79c2694f015e3e781b9a9cbaf1ab9e5fefc/src/modules/FFmpeg/DXVA2OpenGL.cpp#L232C34-L232C49), but it's optimized comparing to what D3D11VA+Vulkan is doing by using DX11 Compute Shader [to copy](https://github.com/zaps166/QMPlay2/blob/615cd79c2694f015e3e781b9a9cbaf1ab9e5fefc/src/modules/FFmpeg/D3D11VAVulkan.cpp#L396). It's not about memory usage, but more GPU usage. Anyway Vulkan+D3D11VA+zero-copy has the lowest GPU usage (maybe same as VkVideo, but can't test VkVideo on my older Intel iGPU).

More memory in D3D11VA can be used because adding `4` more buffers [here](https://github.com/zaps166/QMPlay2/blob/615cd79c2694f015e3e781b9a9cbaf1ab9e5fefc/src/modules/FFmpeg/FFDecD3D11VA.cpp#L64).

**Comment by zaps166** [comment]
> I hope that Vulkan+VkVideo will eventually become the best choice for everyone or you can further improve D3D11VA for Windows.

Yes. I tried VkVideo on Windows on Intel iGPU from 12th gen Core i5 - it works horrible, it's unusable. On AMD with recent drivers is much better, but on RX 6900 XT 4k videos stutters a lot (looks like a driver bug - doesn't use the hardware decoder in optimized way). FullHD videos works fine. On recent Nvidia drivers should be OK I think.

On Linux is a different story, AMD Mesa drivers runs very good (especially since mesa 24.3.1). On Nvidia probably same as on Nvidia on Windows. On Intel - I don't know, need to check, but in the past when I added VkVideo - was bad.

> OK, I understand that different HW decoders are now optimized in different ways, and the optimal combination for each case needs to be selected individually 😄 Thanks for explaining.

Interoperation with DirectX is hard. Maybe is better to use D3D12VA and drop D3D11VA, but it's a lot of work (+ I don't know DirectX and need to use Windows... :sweat_smile:).

**Comment by zaps166** [comment]
Can't reproduce on Radeon Vega 8 integrated GPU.

**Comment by zaps166** [comment]
> This works, but seek doesn't work.

FFmpeg can't seek when video stream is used. MPV also can't seek there.

> I used Nvidia.

Maybe driver bug? :thinking: How is your VRAM usage and how much it grows on every playback restart?

**Comment by zaps166** [comment]
> VLC just does it

Because VLC doesn't play corrupted video stream.

>  next turn on (press O), then the playback cursor will stop again

Because it stops throwing errors.

> Here is a sample video file with audio and video of different lengths

That's expected, it's how this software is working...

> It doubles (only the area used by QMPlay2) after the first repeat, then it remains unchanged. Maybe it really is a driver bug.

I'll check on nvidia.

**Comment by zaps166** [comment]
You want too much changes which needs general rework. Every quick "fix" is a workaround and can break other things. There are corrupted or other uncommon streams which also plays.

**Comment by zaps166** [comment]
> It doubles (only the area used by QMPlay2) after the first repeat, then it remains unchanged. Maybe it really is a driver bug.

My results on your video:
- NVIDIA - yes
- AMD and Intel - no

It should reuse some memory... Maybe Nvidia does something wrong when some memory is freed and allocated again? I don't know if it comes from my code or from FFmpeg - need to check. It's not memory leak, so let's ignore it?

**Comment by zaps166** [comment]
> I just gave an example. You don't have to do anything if it's not appropriate in the current implementation 😅 These examples are extreme cases. I hope that I am not imposing my opinion on you.

Thanks for videos, I stored them for future testing! :+1:

**Comment by zaps166** [comment]
> It doubles (only the area used by QMPlay2) after the first repeat, then it remains unchanged. Maybe it really is a driver bug.

CUVID and VkVideo should be better choice for NVIDIA :smile:

**Comment by zaps166** [comment]
What GPU do you have? Does it support VkVideo? Does it support AV1?

**Comment by zaps166** [comment]
> but look at the bottom of the screen in full screen mode.

Also CUVID? Or VkVideo only?

**Comment by zaps166** [comment]
> All HW decoders except Microsoft (tested on my NVIDIA). There appears a thin bright flashing horizontal line.

It's QMPlay2 bug.

**Comment by zaps166** [comment]
Easy to fix. It's because real video frame height is 1088 and it uses data padding garbage to deinterlace.

**Comment by zaps166** [comment]
Should be fixed now.

**Comment by zaps166** [comment]
Fixed.

**Comment by zaps166** [comment]
Please test if CUVID works and doesn't have new problems.

**Comment by zaps166** [comment]
> I have another [weird sample](https://samples.mplayerhq.hu/V-codecs/VP6/vid.avi) where something is wrong with the frames. QMPlay2 displays a black screen with sound and the playback progress bar does not start. In VLC everything seems to work correctly, the video is not displayed.
> 
> Edit: I also noticed that when a video is on repeat (Alt+1) and `D3D11VA` is used, the amount of video memory used increases after the first repeat. For testing I use H.264 video. This does not happen on other decoders.
> 
> Sorry for the off-topic, I don't want to create a new issue for this 😄 Maybe you can improve this?

This video plays correctly with FFmpeg-master, so I guess it'll be fine when FFmpeg 7.2 will be released.

**Comment by zaps166** [comment]
> I tested it on Windows, everything is fine, thank you! If the bug was in CuvidDec and VulkanYadifDeint, then why was D3D11VA unaffected?

It depends on frame height and what data was in padding data (real frame height is 1088 px, data can be garbage or e.g. zeroed).

**Comment by zaps166** [comment]
If you mix video with garbage data, you'll get video mixed with garbage on output. Maybe D3D11VA was 1080px due to copy to visible width or maybe it was initialized - I didn't check it.

**Comment by zaps166** [comment]
> Maybe this was skipped for better OpenGL and Legacy compatibility since the CUVID module is generic?

It doesn't matter. Done.
